version: "3.3"
services:
  flask_api_service:
    build: .
    ports:
      - 5000:5000
    environment:
      - SECRET=SECRET1
      - SQLALCHEMY_DATABASE_URI=sqlite:////src/db.sqlite
    volumes:
      - .:/usr/my_app
      - ./src/:/src/
    
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./src/:/usr/db/


