version: "3.3"
services:
  flask_api_service:
    build: .
    ports:
      - 5000:5000
    environment:
      - SECRET=SECRET
      - SQLALCHEMY_DATABASE_URI=sqlite:////src/db.sqlite
    # depends_on:
    #   - sqlite3
    volumes:
      - .:/usr/my_app
      - ./src/database/:/src/
    
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./src/database/:/usr/db/
      

